image: node:8.16.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - node -v
          - npm -v
          - yarn -v
          - yarn install
          - yarn test
